version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      nuxt:
        patterns: ["nuxt", "@nuxt/*", "vue", "vue-router"]
      graphql-markdown:
        patterns: ["@graphql-markdown/*"]
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
